#!/usr/bin/env python3
"""Generate src/font.rs from fonts/font8x8_basic.h.

The device stores eight *vertical* pixels per byte, so a glyph column is one byte; the public-domain 8x8
source stores one *row* per byte. This transposes one into the other.

    python3 crates/g13-screen/generators/make-font.py > crates/g13-screen/src/font.rs

The glyph shapes are not ours: they are public domain, by Daniel Hepper, after the public-domain IBM VGA
fonts. Only the transposition and the byte order are this project's.
"""

import re
import sys
from pathlib import Path

SOURCE = "fonts/font8x8_basic.h"

# must match font::ADVANCE and font::GLYPH_ROWS in the generated module
ADVANCE = 6
GLYPH_ROWS = 7
HEADER = """//! An 8x8 font, in the device's own byte order.
//!
//! Generated by `generators/make-font.py` from `fonts/font8x8_basic.h` - do not edit by hand.
//!
//! The LCD stores eight *vertical* pixels per byte (bit 0 is the top), so a glyph column is one byte here.
//! The glyph shapes are public domain, by Daniel Hepper, after the public-domain IBM VGA fonts; they are
//! stored in that header one *row* per byte, and this generator transposes them. The shapes are not ours.
"""

FOOTER = r"""
/// The eight column bytes for a character, or a filled box for one this font does not have.
pub fn glyph(character: char) -> [u8; 8] {
    let code = character as u32;
    if code < 128 {
        GLYPHS[code as usize]
    } else {
        [0xff; 8]
    }
}

/// How far the cursor moves after a character.
///
/// Six, not eight: the glyphs carry their ink in the left five or six columns, and the applets are laid out
/// for this. The longest line among the existing applets is 25 characters, which fits 26 times over at six
/// and overflows the panel at eight.
pub const ADVANCE: usize = 6;
/// Columns of ink a glyph may use.
pub const GLYPH_COLUMNS: usize = 6;
/// Rows of ink a glyph may use.
pub const GLYPH_ROWS: usize = 7;
/// How far apart lines of text are placed, in pixels.
pub const LINE_HEIGHT: usize = 8;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_shapes_survived_the_transpose() {
        // 'A' is solid down its left column, and its top-left pixel is empty
        let a = glyph('A');
        assert!(a[0] != 0, "the left column of A is empty: {a:?}");
        assert_eq!(a[0] & 1, 0, "the top-left pixel of A should be empty");
        // space is blank, so text over a picture leaves the picture's blank pixels blank
        assert_eq!(glyph(' '), [0; 8]);
        // a character outside the table is not silently blank
        assert_eq!(glyph('\u{2500}'), [0xff; 8]);
    }

    #[test]
    fn the_table_is_the_whole_ascii_range() {
        assert_eq!(GLYPHS.len(), 128);
        assert_eq!(glyph(' '), [0; 8]);
        assert_ne!(glyph('!'), [0; 8], "an exclamation mark is not blank");
    }
}
"""


def main() -> int:
    path = Path(__file__).resolve().parent.parent / SOURCE
    text = path.read_text()
    groups = re.findall(r"\{\s*((?:0x[0-9a-fA-F]{2}\s*,\s*){7}0x[0-9a-fA-F]{2})\s*\}", text)
    if len(groups) != 128:
        print("expected 128 glyphs in %s, found %d" % (path, len(groups)), file=sys.stderr)
        return 1

    rows = []
    for code, group in enumerate(groups):
        pixels = [int(value, 16) for value in re.findall(r"0x([0-9a-fA-F]{2})", group)]
        columns = []
        for column in range(8):
            byte = 0
            # columns at or past ADVANCE are dropped: the source glyphs use up to seven, and six is what
            # fits, so keeping the extra ink would make neighbouring characters overlap each other
            if column < ADVANCE:
                # and the eighth row is dropped: the panel's own font is 5 by 7, and text placed at
                # y=35 in an existing applet is meant to finish at row 41, not row 42
                for row in range(min(8, GLYPH_ROWS)):
                    if (pixels[row] >> column) & 1:
                        byte |= 1 << row
            columns.append(byte)
        body = ", ".join("0x%02x" % byte for byte in columns)
        label = repr(chr(code))[1:-1] if 32 <= code < 127 else ""
        rows.append("    [%s], // %3d %s" % (body, code, label))

    print(HEADER)
    print("/// Eight bytes per glyph: one byte per column, bit 0 the top pixel.")
    print("pub const GLYPHS: [[u8; 8]; 128] = [")
    print(",\n".join(rows))
    print("];")
    print(FOOTER)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
